import Mock from 'mockjs'

//图表数据
let list =[]
export default{
    getStatisticalDta:()=>{
        for(let i=0;i<7;i++){
            list.push(
                Mock.mock({
                    苹果:Mock.Random.float(100,500,0,0),
                    vivo:Mock.Random.float(100,500,0,0),
                    oppo:Mock.Random.float(100,500,0,0),
                    魅族:Mock.Random.float(100,500,0,0),
                    三星:Mock.Random.float(100,500,0,0),
                    小米:Mock.Random.float(100,500,0,0),
                })
            )
        }
        return {
            code:2000,
            data:{
                //饼图
                videoData:[
                {
                    name:'苹果',
                    value:9999
                },
                {
                    name:'vivo',
                    value:2999
                },
                {
                    name:'oppo',
                    value:3999
                },
                {
                    name:'魅族',
                    value:4999
                },
                {
                    name:'三星',
                    value:1299
                },
                {
                    name:'小米',
                    value:4899
                }
            ],
            //柱状图
            userData:[
                {
                    date:'周一',
                    new:55,
                    active:200
                },
                {
                    date:'周二',
                    new:100,
                    active:1000
                },
                {
                    date:'周三',
                    new:12,
                    active:300
                },
                {
                    date:'周四',
                    new:83,
                    active:800
                },
                {
                    date:'周五',
                    new:210,
                    active:1000
                },
                {
                    date:'周六',
                    new:115,
                    active:590
                },
                {
                    date:'周日',
                    new:30,
                    active:2000
                }
            ],
            //折线图
            orderData:{
                date:['20211001','20201002','20201003','20201004','20201005','20201006','20201007'],
                data:list
            },
            tableData:[
                {
                  name:'oppo',
                  todayBuy:100,
                  monthBuy:200,
                  totalBuy:500
                },
                {
                  name:'vivo',
                  todayBuy:200,
                  monthBuy:200,
                  totalBuy:5000
                },
                {
                  name:'Apple',
                  todayBuy:300,
                  monthBuy:1100,
                  totalBuy:5580
                },
                {
                  name:'华为',
                  todayBuy:500,
                  monthBuy:2880,
                  totalBuy:566000
                },
                {
                  name:'redMi',
                  todayBuy:180,
                  monthBuy:2330,
                  totalBuy:54440
                },
                {
                  name:'三星',
                  todayBuy:160,
                  monthBuy:250,
                  totalBuy:5000
                }
              ]
            }

        }
    }
}